# Generated by Django 4.2.1 on 2023-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("rate_limit_value", models.IntegerField()),
                ("rate_limit_type", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="DictWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=64)),
                ("origin", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(default=None, max_length=256, null=True),
                ),
                ("exchange", models.CharField(default=None, max_length=256, null=True)),
                ("name", models.CharField(max_length=256)),
                ("industry", models.CharField(default=None, max_length=256, null=True)),
                ("integration", models.CharField(default=None, max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("is_in_dictionary", models.BooleanField(default=False)),
                ("ipo_date", models.CharField(default=None, max_length=256, null=True)),
                (
                    "status",
                    models.CharField(default="active", max_length=64, null=True),
                ),
                ("ticker", models.CharField(default=None, max_length=64, null=True)),
                ("wiki_page", models.CharField(default=None, max_length=256)),
                ("wiki_page_views", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="registeredcompany",
            constraint=models.UniqueConstraint(
                fields=("name", "ticker"), name="name__ticker__unique_together"
            ),
        ),
        migrations.AddConstraint(
            model_name="dictword",
            constraint=models.UniqueConstraint(
                fields=("value", "origin"), name="unique_word_per_origin"
            ),
        ),
        migrations.AddConstraint(
            model_name="dictionary",
            constraint=models.UniqueConstraint(
                fields=("base_url", "name"), name="unique__dict__api"
            ),
        ),
    ]
