# Generated by Django 4.2.1 on 2023-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_dictionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="rate_limit_type",
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dictionary",
            name="rate_limit_value",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
